Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  config.vm.define "nginx-server"
  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name="nginx-server"
    vb.cpus=1
    vb.memory = "1024"
   end

config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y nginx
    sed -i 's/80/82/g' /etc/nginx/sites-enabled/default
    systemctl restart nginx
   SHELL
end
